spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      path: /h2
      enabled: true

logging:
  level:
    org.springframework.jdbc: debug